// AT-MEC_HM_8.0_AI_READY_ENTERPRISE_STABLE
window.ATMEC_VERSION_LABEL='AT-MEC_HM_8.0_AI_READY_ENTERPRISE_STABLE';
window.AT_MEC_RELEASE='AT-MEC_HM_8.0_AI_READY_ENTERPRISE_STABLE';
window.AT_MEC_VERSION='8.0.0';
