// AT-MEC_HM_10.1.12_STABLE_ACTION_UNIQUE_FAST_START_FIX
window.ATMEC_VERSION_LABEL='AT-MEC_HM_10.1.12_STABLE_ACTION_UNIQUE_FAST_START_FIX';
window.AT_MEC_RELEASE='AT-MEC_HM_10.1.12_STABLE_ACTION_UNIQUE_FAST_START_FIX';
window.AT_MEC_VERSION='10.1.12';
