const fs=require('fs'); const path=require('path'); const root=process.cwd();
function exists(p){return fs.existsSync(path.join(root,p));} function txt(p){try{return fs.readFileSync(path.join(root,p),'utf8')}catch{return ''}} function js(p){try{return JSON.parse(fs.readFileSync(path.join(root,p),'utf8'))}catch{return {}}}
const index=txt('src/renderer/index.html'); const local=js('database/ate_mec_local_db.json'); const ent=js('database/ate_mec_enterprise_db.json'); const checks=[]; function check(label,ok,detail=''){checks.push({label,ok:!!ok,detail});}
check('No legacy 6.0/6.1 runtime',!/work-order-product-60\.js|revision-firmware-61\.js/.test(index),'legacy non caricati');
check('Menu AI semplificato mantenuto',/showAiChat952|AI Copilot/.test(index),'AI menu presente');
check('Test Mode topbar strict CSS presente',/43-testmode-topbar-strict-953\.css/.test(index)&&exists('src/renderer/css/modules/43-testmode-topbar-strict-953.css'),'topbar strict');
check('Utenti clean production',exists('config/users.json')&&/"Admin"/.test(txt('config/users.json'))&&/"Tecnico"/.test(txt('config/users.json')),'Admin/Tecnico');
check('Ricette e storico puliti',Array.isArray(local.recipes)&&local.recipes.length===0&&Array.isArray(local.testReports)&&local.testReports.length===0&&Array.isArray(local.repairs)&&local.repairs.length===0,'local db zero');
const t=ent.tables||{}; check('Enterprise dati produzione puliti',Array.isArray(t.recipes)&&t.recipes.length===0&&Array.isArray(t.test_results)&&t.test_results.length===0&&Array.isArray(t.repairs)&&t.repairs.length===0,'enterprise zero');
check('Driver manager 10.0',exists('drivers/INSTALLA_DRIVER_HARDWARE_10.0.bat')&&exists('drivers/CHECK_DRIVER_HARDWARE_10.0.bat'),'driver scripts');
const score=Math.round(checks.filter(c=>c.ok).length/checks.length*100); const report={version:'AT-MEC_HM_10.0_ENTERPRISE_STABLE_CLEAN_PRODUCTION_WITH_DRIVERS',createdAt:new Date().toISOString(),score,checks}; fs.mkdirSync(path.join(root,'docs/quality'),{recursive:true}); fs.writeFileSync(path.join(root,'docs/quality/AT_MEC_HM_10_0_CLEANUP_AUDIT.json'),JSON.stringify(report,null,2)); console.log(`AT-MEC HM 10.0 cleanup audit: ${score}%`); checks.forEach(c=>console.log(`${c.ok?'OK  ':'FAIL'} ${c.label}${c.detail?' - '+c.detail:''}`)); if(score<100) process.exit(1);
