const fs=require('fs'); const path=require('path'); const crypto=require('crypto');
const root=process.cwd(); const now=new Date().toISOString();
function write(p,obj){fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),JSON.stringify(obj,null,2));}
function hash(password){const salt=crypto.randomBytes(16).toString('hex'); const key=crypto.scryptSync(password,Buffer.from(salt,'hex'),64).toString('hex'); return {salt,passwordHash:`scrypt$${salt}$${key}`};}
const admin=hash('Criicket@Hasnaiin@786!'); const tec=hash('Tecnico@786!');
const adminPerms=['run_test','view_reports','debug_mode','edit_recipe','config_hardware','manage_users','manage_branding','edit_layout','show_ui_ids','test_elements','view_traceability','view_kpi','manage_data','sign_quality','approve_reports','manage_ai','config_ai','reset_data','manage_work_orders','manage_repair','export_data','import_data','factory_admin','runtime_validate','startup_doctor','driver_install','driver_check'];
const tecPerms=['run_test','view_reports','debug_mode','view_traceability','view_kpi','manage_repair','ai_read','export_data'];
const roles={Operator:{permissions:['run_test','view_reports'],level:10},Tecnico:{permissions:tecPerms,level:30},Technician:{permissions:tecPerms,level:30},Engineer:{permissions:['run_test','view_reports','debug_mode','edit_recipe','config_hardware','view_traceability','view_kpi','manage_data','manage_repair','ai_read','export_data'],level:60},Developer:{permissions:['run_test','view_reports','debug_mode','edit_recipe','config_hardware','manage_branding','edit_layout','show_ui_ids','test_elements','view_traceability','view_kpi','manage_data','manage_ai','config_ai','export_data'],level:80},Admin:{permissions:adminPerms,level:100},Qualità:{permissions:['view_reports','sign_quality','approve_reports','view_kpi','view_traceability','ai_read'],level:60}};
const users=[{username:'Admin',displayName:'Admin',role:'Admin',salt:admin.salt,passwordHash:admin.passwordHash,enabled:true,operatorCode:'ADMIN'},{username:'Tecnico',displayName:'Tecnico',role:'Tecnico',salt:tec.salt,passwordHash:tec.passwordHash,enabled:true,operatorCode:'TECNICO'}];
write('config/users.json',{roles,users});
write('database/ate_mec_local_db.json',{schemaVersion:1,createdAt:now,updatedAt:now,environment:'clean_production_10_0',recipes:[],testReports:[],repairs:[]});
const perms=[]; for(const [role,r] of Object.entries(roles)){for(const p of r.permissions)perms.push({role,permission:p,id:`${role.toLowerCase()}_${p}`,createdAt:now,updatedAt:now});}
write('database/ate_mec_enterprise_db.json',{schemaVersion:100000,createdAt:now,updatedAt:now,backend:'json_enterprise',sqliteReady:false,environment:'clean_production_10_0',tables:{users:users.map(u=>({...u,id:u.username.toLowerCase(),createdAt:now,updatedAt:now})),roles:Object.entries(roles).map(([role,r])=>({role,permissions:r.permissions,level:r.level,id:role.toLowerCase(),createdAt:now,updatedAt:now})),permissions:perms,recipes:[],recipe_versions:[],test_results:[],test_steps:[],serial_history:[],firmware_history:[],repairs:[],devices:[],device_events:[],device_configs:[],production_stats:[],quality_stats:[],work_orders:[],ai_messages:[],ai_action_queue:[]}});
write('database/sync_queue.json',{schemaVersion:1,updatedAt:now,items:[]});
for(const d of ['recipes','certificates','backups']){const dir=path.join(root,d); fs.rmSync(dir,{recursive:true,force:true}); fs.mkdirSync(dir,{recursive:true}); fs.writeFileSync(path.join(dir,'README_PRODUCTION_CLEAN.txt'),'Cartella pulita produzione 10.0.\n');}
console.log('AT-MEC HM 10.0 produzione pulita ripristinata. Utenti: Admin / Tecnico.');
